name: 'Flake8 action'
description: 'Run flake8 and annotate the results'
author: 'suo'
branding:
  icon: check-circle
  color: yellow
inputs:
  checkName:
    description: 'The name of the check to add annotations to.

      Generally the same as the job that uses this action'
    required: true
runs:
  using: node20
  main: dist/index.js
